# Generated by Django 4.0.4 on 2022-06-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0002_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=30)),
                ('Standard', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
    ]
