# Generated by Django 4.0.4 on 2022-06-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roll_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
