# Generated by Django 4.0.4 on 2022-06-20 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_remove_user_roll_number_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='sid',
        ),
    ]
